In [1]:
using Revise
using NamedTrajectories
using QuantumCollocation
using LinearAlgebra
using SparseArrays

In [48]:
levels = [3, 3]

2-element Vector{Int64}:
 3
 3

In [49]:
N = prod(levels)
U = reshape(1:N^2, N, N)
U += im * (U .+ N^2)
U

9×9 Matrix{Complex{Int64}}:
 1+82im  10+91im  19+100im  28+109im  …  55+136im  64+145im  73+154im
 2+83im  11+92im  20+101im  29+110im     56+137im  65+146im  74+155im
 3+84im  12+93im  21+102im  30+111im     57+138im  66+147im  75+156im
 4+85im  13+94im  22+103im  31+112im     58+139im  67+148im  76+157im
 5+86im  14+95im  23+104im  32+113im     59+140im  68+149im  77+158im
 6+87im  15+96im  24+105im  33+114im  …  60+141im  69+150im  78+159im
 7+88im  16+97im  25+106im  34+115im     61+142im  70+151im  79+160im
 8+89im  17+98im  26+107im  35+116im     62+143im  71+152im  80+161im
 9+90im  18+99im  27+108im  36+117im     63+144im  72+153im  81+162im

In [50]:
subspace_inds = subspace_indices(levels)
leakage_inds = subspace_leakage_indices(levels)

5-element Vector{Int64}:
 3
 6
 7
 8
 9

In [51]:
U[leakage_inds, subspace_inds]

5×4 Matrix{Complex{Int64}}:
 3+84im  12+93im  30+111im  39+120im
 6+87im  15+96im  33+114im  42+123im
 7+88im  16+97im  34+115im  43+124im
 8+89im  17+98im  35+116im  44+125im
 9+90im  18+99im  36+117im  45+126im

In [52]:
Ũ⃗ = operator_to_iso_vec(U)

162-element Vector{Float64}:
   1.0
   2.0
   3.0
   4.0
   5.0
   6.0
   7.0
   8.0
   9.0
  82.0
   ⋮
 154.0
 155.0
 156.0
 157.0
 158.0
 159.0
 160.0
 161.0
 162.0

In [55]:
iso_leakage_inds = unitary_isomorphism_leakage_indices(levels)
for i = axes(Ũ⃗, 1) 
    if i ∉ iso_leakage_inds
        Ũ⃗[i] = 0
    end
end
Matrix{Complex{Int}}(iso_vec_to_operator(Ũ⃗))

9×9 Matrix{Complex{Int64}}:
 0+0im    0+0im   0+0im   0+0im     0+0im    0+0im  0+0im  0+0im  0+0im
 0+0im    0+0im   0+0im   0+0im     0+0im    0+0im  0+0im  0+0im  0+0im
 3+84im  12+93im  0+0im  30+111im  39+120im  0+0im  0+0im  0+0im  0+0im
 0+0im    0+0im   0+0im   0+0im     0+0im    0+0im  0+0im  0+0im  0+0im
 0+0im    0+0im   0+0im   0+0im     0+0im    0+0im  0+0im  0+0im  0+0im
 6+87im  15+96im  0+0im  33+114im  42+123im  0+0im  0+0im  0+0im  0+0im
 7+88im  16+97im  0+0im  34+115im  43+124im  0+0im  0+0im  0+0im  0+0im
 8+89im  17+98im  0+0im  35+116im  44+125im  0+0im  0+0im  0+0im  0+0im
 9+90im  18+99im  0+0im  36+117im  45+126im  0+0im  0+0im  0+0im  0+0im

In [45]:
iso_leakage_inds

4-element Vector{Any}:
  3
  6
  9
 12